### ISSUE TITLE
Question about start.sh

### ISSUE THREAD

**Issue by abusimbele** [coppit/docker-mumble-server#2]
**What's the purpose of the infinity loop at the end?:**

![image](https://cloud.githubusercontent.com/assets/452955/25496099/03ae17ca-2b80-11e7-9b9d-42523f89eec1.png)

https://github.com/coppit/docker-mumble-server/blob/master/start.sh#L17

**Comment by evilstiefel** [comment]
I think the point is that otherwise, the mumble server would stop again, because you are not switching to another process (meaning: as soon as start.sh is finished, the docker container would exit again).

So, you can either do something like "exec" and switch the process over to something else that runs in the foreground, or just keep the start.sh-"bash-process" running.

**Comment by coppit** [comment]
Yes. The container exits when the command completes. This prevents that. That said, after learning more about the Phusion baseimage, they have a better way to do it -- just drop a script into /etc/service. When I do another update, I'll probably switch to that mechanism. (But I'm using Discord now, which is much better than Mumble.)
